### ISSUE TITLE
Verifly/remove 21608910, 21410963, 19526332 ids from archive browse portion(s)

### ISSUE THREAD

**Issue by jheasly** [rgpages/summer-events#3]
These are local (& wire) previews and are almost always obsolete.  
Arts -> Music 21608910; generally AP wire copy
Entertainment -> Music 21410963; generally a preview, so it's already happened and is best covered by Go! editors picks forecast calendar  

Don't even know if this IDs in any request, but ... 
Encore -> Music 19526332; a dead/dropped/obsolete section

**Comment by robertdenton** [comment]
Done, thanks, closing.
